theme[main_bg]="#fbf1c7"
theme[main_fg]="#3c3836"
theme[title]="#282828"
theme[hi_fg]="#9d0006"
theme[selected_bg]="#ebdbb2"
theme[selected_fg]="#282828"
theme[inactive_fg]="#7c6f64"
theme[graph_text]="#504945"
theme[meter_bg]="#d5c4a1"
theme[proc_misc]="#427b58"

theme[cpu_box]="#b57614"
theme[mem_box]="#076678"
theme[net_box]="#79740e"
theme[proc_box]="#8f3f71"
theme[div_line]="#bdae93"

theme[temp_start]="#b57614"
theme[temp_mid]="#af3a03"
theme[temp_end]="#9d0006"

theme[cpu_start]="#79740e"
theme[cpu_mid]="#98971a"
theme[cpu_end]="#b8bb26"

theme[free_start]="#076678"
theme[free_mid]="#458588"
theme[free_end]="#83a598"

theme[cached_start]="#8f3f71"
theme[cached_mid]="#b16286"
theme[cached_end]="#d3869b"

theme[available_start]="#b57614"
theme[available_mid]="#d79921"
theme[available_end]="#fabd2f"

theme[used_start]="#9d0006"
theme[used_mid]="#cc241d"
theme[used_end]="#fb4934"

theme[download_start]="#79740e"
theme[download_mid]="#98971a"
theme[download_end]="#b8bb26"

theme[upload_start]="#79740e"
theme[upload_mid]="#98971a"
theme[upload_end]="#b8bb26"
